### ISSUE TITLE
Sub Clauses

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/lrw-udd-api#5] opened 2016-05-05 13:14 UTC
Does the query syntax support additional clauses, e.g. if i wanted to query a *range* of updatedDt’s, the logical equiv of ($gte low AND $lt high)

**Comment by amason** [comment] 2016-05-06 16:02
I received feedback from Andrew advising this:

Yep https://jiscv2.learninglocker.net/api/jisc/v1.2.1/student?populate="studentAdditional"&query={"UPDATED_AT":{"$gte":"2016-05-01T00:00:00.000Z","$lt":"2016-05-10T00:00:00.000Z"}}

**Comment by amason** [comment] 2016-05-06 16:05
In working with Russ - this answers his question. Closing this out as the issue is resolved.

**Closed** 2016-05-09 09:24 UTC
Labels: help wanted
